### ISSUE TITLE
Please consider renaming the starter

### ISSUE THREAD

**Issue by snicoll** [infinispan/infinispan-spring-boot#3]
Hello,

Thanks for writing this, this looks quite interesting. We have [some rules for 3rd party starters](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming). Could you please review them and rename your modules accordingly?

I can see this project is named `infinispan-spring-boot`(:+1:). Naming your starter `inifinispan-spring-boot-starter` is what we would expect.

Thanks!

**Comment by snicoll** [comment]
Also, please don't use the `spring` namespace for 3rd party properties. 

Did you consider submitting those changes to the spring boot project itself? I had a quick look and we would have to rework it so that it only kicks in where we are sure the user wants inifinispan. If the embedded part is in a separate jar, that may be enough....

**Comment by slaskawi** [comment]
Hey @snicoll,

Thanks a lot for the review! All comments addressed: https://github.com/infinispan/infinispan-spring-boot/pull/5

Long, long time ago when we were writing first Infinispan-Spring integration bits we had a discussion where to put them. Since they are tied more to our release cycle we decided to implement them in our repository. We decided follow this path also with Spring Boot and Spring Session. In the retrospect, we're quote happy with this decision.

I'm not sure if I understand you correctly... you're saying that we should initialize all the bits only if Infinispan is on the classpath? If that is so, I can make it `<optional>true</optional>` (there's also `@ConditionalOnClass(CacheContainer.class)` so it should do the trick).

BTW - once those starters are released I plan to add them [here](https://github.com/spring-io/initializr/blob/master/initializr-service/src/main/resources/application.yml). I hope that would be fine.

Thanks,
Sebastian

**Comment by snicoll** [comment]
Thanks for working on this!

Couldn't you embed infinispan or connect to an instance? If so, checking if the "server" classes are present (and make them optional) would be sensible IMO. I don't know it much so I am guessing at this point. Happy to help if you have questions.

**Comment by snicoll** [comment]
We don't have a caching group on initializr yet so I am afraid that's not going to work for now.

**Comment by slaskawi** [comment]
@snicoll I think I get you now... 

Infinispan can work in 2 different modes - embedded (along with your app; this starter uses this mode) and client/server mode (a standalone server plus a client for it). Currently the starter uses only the former.

At first I didn't want to implement the latter (client/server) since it would require exactly the same configuration as our integration point. But after thinking about this for a while, I will implement add it (for symmetry reasons).

RT initializr - I thought about putting it under `Cloud Cluster` category. It already contains `Cluster Redis`, `Cluster Zookeeper` and `Cluster Hazelcast`, so Infinispan fits there perfectly.

**Comment by snicoll** [comment]
It does not. These are specific Spring Cloud projects.

**Comment by slaskawi** [comment]
Ok, thanks a lot for the hint. I'll look into those as soon as I finish the starters.
