### ISSUE TITLE
Implement Client/Server mode

### ISSUE THREAD

**Issue by slaskawi** [infinispan/infinispan-spring-boot#6]
Created based on discussion: https://github.com/infinispan/infinispan-spring-boot/issues/3

**Comment by snicoll** [comment]
I'd like this to be the same starter. If the embedded library is present that mode should kick in. Otherwise the client/server mode should apply. That way you have a single starter (important!) and adding the embedded library is all that is needed. 

This is how our JMS support works. Maybe you need a bom as well for dependencies?

**Comment by slaskawi** [comment]
The idea sounds really great!

**Comment by slaskawi** [comment]
The code: https://github.com/infinispan/infinispan-spring-boot/pull/7
An Embedded usage: https://github.com/infinispan/infinispan-simple-tutorials/pull/20
A Remote usage: https://github.com/infinispan/infinispan-simple-tutorials/pull/20

**Comment by slaskawi** [comment]
@snicoll After this gets in, I plan to release the Starters. 

Please let me know if there's anything else you'd like me to look into.

**Comment by snicoll** [comment]
Can you give me a few days to look into it please? I am supponsingly off the grid this week.
